In [1]:
import numpy as np

In [3]:
a = np.array([[2,1],[3,2],[2,1],[5,1]])

b = np.cov(a.T)
b

array([[2.  , 0.  ],
       [0.  , 0.25]])

In [48]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [51]:
a.shape
a.size
a.dtype

dtype('int32')

np.array, np.zeros, np.zeros_like, np.ones, ones_like, np.empty, empty_like, np.arange, np.linspace

all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where .

### Indexing, Slicing
- b.flatten()
- for i in b.flat:
    print(i)
- np.where 

- a[:, newaxis]


### Shape Manipulation
- a.shape, a.reshape, a.resize, a.ravel()
- a.ravel() - returns the array, flattened
- a.reshape(6,2)
- a.T
- The reshape function returns its argument with a modified shape, 
    whereas the ndarray.resize method modifies the array itself.
- a.reshape(3,-1), #-1 when we do not dimension of other axis


### Stacking
- column_stack == hstack
- hstack
- vstack
- hsplit
- vsplit
- a.copy() - Deep copy
- a.view()


In [54]:
### Conversion
a.astype("int")

array([1, 2, 3])

In [3]:
l = [ [10,20,30], [1,2,3]]
l

[[10, 20, 30], [1, 2, 3]]

In [4]:
np.array(l)

array([[10, 20, 30],
       [ 1,  2,  3]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.arange(10,20,4)

array([10, 14, 18])

In [9]:
np.linspace(10,20,3)

array([10., 15., 20.])

In [10]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
x = np.random.random((3,4))
x

array([[0.11812382, 0.31584202, 0.72171171, 0.77559747],
       [0.43012737, 0.58736314, 0.64427811, 0.85697416],
       [0.47213138, 0.74998646, 0.60008744, 0.79613998]])

In [12]:
np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

array([[ 1,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 14, 16]])

In [13]:
np.asarray([202,30,4])

array([202,  30,   4])

In [17]:
m = [2.3,2.8,3.9]
np.round(m)

array([2., 3., 4.])

In [20]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [42]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
b

array([[8, 1, 7],
       [4, 3, 9],
       [5, 2, 6]])

In [43]:
np.apply_along_axis(sorted,1,b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

[8, 1, 7, 4, 3, 9, 5, 2, 6]

In [44]:
x = np.array([[[0], [1], [2]]])

In [45]:
x

array([[[0],
        [1],
        [2]]])

In [46]:
x.squeeze()

array([0, 1, 2])

In [56]:
from sklearn.datasets import fetch_20newsgroups

In [58]:
data = fetch_20newsgroups(subset='train')